spring:
  application.name: spring-app
  profiles.active: dev
  datasource.url: jdbc:h2:mem:testdb
  datasource.driverClassName: org.h2.Driver
  datasource.username: sa
  datasource.password: sa
  liquibase.change-log: db/changelog/db.changelog-master.xml
  jpa.show-sql: true
  activemq:
    in-memory: true
    packages:
      trusted: ru.tinkoff.fintech.homework.homework13
server.port: 9000

person.information.address: http://localhost:9001

cron: "0 0 * * * *"
